from datetime import date
from os import name




DTYPES = {
        'customer_name': 'string',
        'father_name': 'string', 
        'customer_profile': 'string', 
        'loan_account_no': 'string', 
        'due_date': 'string',
        'due_prop_no': 'string', 
        'due_agmt_no': 'string', 
        'risk_status': 'string',
        'last_disposition': 'string',
        'last_disposition_date': 'string',
        'assigned_date': 'string',
        'product_name': 'string',
        'first_called_date': 'string',
        'customer_pincode': 'string', 
        'customer_landmark': 'string', 
        'customer_address1': 'string', 
        'customer_address2': 'string', 
        'customer_address3': 'string', 
        'customer_city': 'string', 
        'batch_id': 'int',
        'client_id': 'int',
        'customer_state': 'string', 
        'customer_region': 'string', 
        'customer_zone': 'string', 
        'customer_mobile_number': 'string', 
        'customer_alt_contact_no': 'string', 
        'office_pincode': 'string', 
        'office_landmark': 'string', 
        'office_address1': 'string', 
        'office_address2': 'string', 
        'office_address3': 'string', 
        'office_city': 'string', 
        'office_state': 'string', 
        'office_region': 'string', 
        'office_zone': 'string', 
        'office_mobile_no': 'string', 
        'disbursal_date': 'string', 
        'last_collection_date': 'string', 
        'first_emi_date': 'string', 
        'last_emi_date': 'string', 
        'agening': 'string', 
        'last_collection_gap_category': 'string', 
        'cheque_bounce': 'string', 
        'cash_bounce': 'string', 
        'score_category': 'string', 
        'segment': 'string', 
        'od_movement': 'string', 
        'unmatured_tenor': 'string', 
        'opening_dpd': 'string', 
        'opening_dpd_bracket': 'string', 
        'payment_frequency': 'string', 
        'dpd_del_string': 'string', 
        'closing_dpd': 'string', 
        'closing_dpd_bracket': 'string', 
        'guarantor_name': 'string', 
        'guarantor_address1': 'string', 
        'guarantor_address2': 'string', 
        'guarantor_address3': 'string', 
        'guarantor_city': 'string', 
        'guarantor_landmark': 'string', 
        'guarantor_pincode': 'string', 
        'loan_amount': 'string', 
        'agreement_date': 'string', 
        'lrn': 'string', 
        'tenor': 'string', 
        'adv_emi': 'string', 
        'mob': 'string', 
        'bkt': 'string', 
        'emi': 'string', 
        'demand': 'string', 
        'receivable': 'string', 
        'received': 'string', 
        'over_due': 'string', 
        'total_charges': 'string', 
        'total_od': 'string', 
        'future_princ': 'string', 
        'pos': 'string', 
        'amount_finanaced': 'string', 
        'ltv': 'string', 
        'morat_type': 'string', 
        'status': 'string', 
        'payment_type': 'string', 
        'insurance_type': 'string', 
        'cbd_receivable': 'string', 
        'cbd_received': 'string', 
        'cbd_waived': 'string', 
        'cbc_due': 'string', 
        'afc_receivable': 'string', 
        'afc_received': 'string', 
        'afc_waived': 'string', 
        'afc_due': 'string', 
        'cash_bnc_receivable': 'string', 
        'cash_bnc_received': 'string', 
        'cash_bnc_waived': 'string', 
        'cash_bnc_due': 'string', 
        'ins_receivable': 'string', 
        'ins_received': 'string', 
        'ins_due': 'string', 
        'clearing_receivable': 'string', 
        'clearing_received': 'string', 
        'clearing_due': 'string', 
        'od_collectable': 'string', 
        'demand_collectable': 'string', 
        'future_outstanding': 'string', 
        'asset_cost': 'string', 
        'scheme_code': 'string', 
        'scheme_name': 'string'
}



{
    "ZONE_NAME": "zone_name",
    "REGION_NAME": "region_name",
    "BRAN_CODE": "batch_code",
    "AREANAME": "first_name",
    "BRANACHNAME": "batch_name",
    "DUE AGMT NO": "due_agmt_no",
    "TENOR": "tenor",
    "ADVEMI": "adv_emi",
    "MOB": "mob",
    "BKT": "bkt",
    "EMI": "emi",
    "DEMAND": "demand",
    "OVERDUE": "overdue",
    "TOTAL CHARGES": "total_charges",
    "TOTAL OD ( OD + CHARGES )": "total_od",
    "FUTURE_PRINC": "future_princ",
    "POS ( OD + FP )": "pos",
    "ADDRESS": "customer_address1",
    "Mobile Number": "customer_mobile_number",
    "Alternate Number": "alt_contact_number",
    "FIRST_EMI_DATE": "first_emi_date",
    "LAST_EMI_DATE": "last_emi_date",
    "AMOUNT_FINANACED": "amount_finanaced",
    "DISBURSAL_DATE": "disbursal_date",
    "PRODUCTGROUP": "product_group",
    "STATUS": "status",
    "PAYMENTTYPE": "payment_type",
    "CITY": "customer_city",
    "PINCODE": "customer_pincode",
    "LANDMARK": "customer_landmark",
    "OFC_ADDRESS1": "office_address1",
    "OFC_ADDRESS2": "office_address2",
    "OFC_ADDRESS3": "office_address3",
    "OFC_PINCODE": "office_pincode",
    "OFC_MOBILENO": "office_mobile_number",
    "MODEL": "model",
    "REG_NUMBER": "reg_no",
    "CHASSIS_NO": "chassis_no",
    "ENG_NO": "eng_no",
    "LAST_COLL_DATE": "last_collection_date",
    "LTV": "ltv",
    "LOAN_AMOUNT": "loan_amount",
    "CUST_PROFILE": "customer_profile",
    "MORAT_TYPE": "morat_type",
    "Customer Name": "customer_name",
    "Loan Account No": "loan_account_no",
    "DUE DATE"    : "due_date",
    "FATHER NAME": "father_name",
    "DUE PROP NO": "due_prop_no",
    "Product Name": "product_name"
}

